[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "yarn build-preview"

#https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

[[redirects]]
  from = "/principle"
  to = "/"
  status = 301
  #force = false
  #query = {path = ":path"}

[[redirects]]
  #from = "/support"
  #to = "/"
  #status = 301

[[redirects]]
  from = "/areas"
  to = "/"
  status = 301

[[redirects]]
  from = "/levels"
  to = "/"
  status = 301

[[redirects]]
  from = "*"
  to = "/"
  status = 404
